"""alter links table (is_public -> status)

Revision ID: 4ea32de0a2ed
Revises: 3704e3875d3b
Create Date: 2021-11-07 12:26:28.306374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ea32de0a2ed'
down_revision = '3704e3875d3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('status', sa.String(length=10), nullable=False))
    op.drop_column('link', 'is_public')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('link', sa.Column('is_public', sa.VARCHAR(length=1), nullable=False))
    op.drop_column('link', 'status')
    # ### end Alembic commands ###
